name: Run Consul Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  Consul-Pipeline:
    uses: Netcracker/qubership-test-pipelines/.github/workflows/consul.yaml@update_images
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      versions_file: '.github/versions.yaml'
      pipeline_branch: 'update_images' #this value must match the value after '@' in 'uses'
